In [1]:
import pandas as pd
import numpy as np 
import json

In [2]:
df = pd.read_json('../../input/dados.json')
df

                                             pessoas
0  {'nome': 'João', 'idade': '25', 'endereco': {'...
1  {'nome': 'Maria', 'idade': 30, 'endereco': {'r...

In [5]:
with open('../../input/dados.json', 'r') as file:
    data = json.load(file)

df = pd.json_normalize(data['pessoas'])
df

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo
1,Maria,30,[21 3333-3333],,456,Rio de Janeiro

In [6]:
df = df.explode('telefones')
df

    nome idade     telefones endereco.rua  endereco.numero endereco.cidade
0   João    25  11 1111-1111        Rua A              123       São Paulo
0   João    25  11 2222-2222        Rua A              123       São Paulo
1  Maria    30  21 3333-3333                           456  Rio de Janeiro

In [8]:
df['endereco.rua'].unique()

array(['Rua A', ''], dtype=object)

In [9]:
df_without_empty = df[df['endereco.rua'] != ''].copy()
df_without_empty

   nome idade     telefones endereco.rua  endereco.numero endereco.cidade
0  João    25  11 1111-1111        Rua A              123       São Paulo
0  João    25  11 2222-2222        Rua A              123       São Paulo

In [10]:
df_without_empty.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 0
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      object
 1   idade            2 non-null      object
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      object
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      object
dtypes: int64(1), object(5)
memory usage: 112.0+ bytes

In [11]:
columns_to_convert = ['idade', 'endereco.numero']
df_without_empty[columns_to_convert] = df_without_empty[columns_to_convert].astype(np.int64)

In [ ]:
columns_to_convert_str = ['idade', 'endereco.numero']

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 0 to 0
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      object
 1   idade            2 non-null      int64
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      object
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      object
dtypes: int64(2), object(4)
memory usage: 112.0+ bytes